Repository mhvk/baseband, pull requests merged in 2018-05, with the labels that each got.

#198 General opener, using file info.
  CHANGES.rst
  baseband/__init__.py
  baseband/core.py
  baseband/tests/test_core.py
  baseband/tests/test_file_info.py
  baseband/vlbi_base/file_info.py
  docs/data/index.rst
  docs/index.rst
  docs/tutorials/getting_started.rst
Labels: enhancement

#223 Changed __index__ to operator.index
  baseband/mark4/frame.py
  baseband/vlbi_base/base.py
  baseband/vlbi_base/payload.py
Labels: refactoring

#230 Minor doc and docstring changes.
  baseband/mark5b/base.py
  docs/dada/index.rst
  docs/gsb/index.rst
  docs/mark4/index.rst
  docs/mark5b/index.rst
  docs/tutorials/getting_started.rst
  docs/vdif/index.rst
Labels: docs

#229 Allow passing of header in place of bps to VLBIPayloadBase.fromdata.
  baseband/dada/frame.py
  baseband/vdif/payload.py
  baseband/vlbi_base/payload.py
  baseband/vlbi_base/tests/test_vlbi_base.py
Labels: refactoring
