Repository mhvk/baseband, pull requests merged in 2018-06, with the labels that each got.

#212 Implemented GUPPI support
  baseband/data/__init__.py
  baseband/data/sample_puppi.raw
  baseband/guppi/__init__.py
  baseband/guppi/base.py
  baseband/guppi/frame.py
  baseband/guppi/header.py
  baseband/guppi/payload.py
  baseband/guppi/tests/__init__.py
  baseband/guppi/tests/test_guppi.py
  docs/guppi/index.rst
  docs/index.rst
Labels: guppi

#237 Add GUPPI to changelog.
  CHANGES.rst
Labels: docs

#239 Minor addition to GUPPI docs.
  docs/guppi/index.rst
Labels: docs

#243 Added PR #240 to changelog.
  CHANGES.rst
Labels: docs

#242 Add check for reading partial last GUPPI frame
  baseband/guppi/tests/test_guppi.py
Labels: guppi, testing

#233 Allow user to choose whether stream readers verify frames.
  CHANGES.rst
  baseband/dada/base.py
  baseband/gsb/base.py
  baseband/guppi/base.py
  baseband/mark4/base.py
  baseband/mark5b/base.py
  baseband/vdif/base.py
  baseband/vdif/tests/test_vdif.py
  baseband/vlbi_base/base.py
  baseband/vlbi_base/tests/test_vlbi_base.py
Labels: enhancement

#241 Speed up verify
  CHANGES.rst
  baseband/mark4/header.py
  baseband/mark5b/header.py
  baseband/vdif/frame.py
  baseband/vdif/header.py
  docs/tutorials/new_edv.rst
Labels: performance

#246 Set version to 2.0.dev
  CHANGES.rst
  setup.cfg
Labels: release

#247 Increase depth of overview section
  docs/index.rst
  docs/install.rst
Labels: docs
